image: node:lts

stages:
  - test

Unit Tests:
  stage: test
  script:
   - npm ci
   - npm run test:unit

Integration Tests:
  stage: test
  script:
   - npm ci
   - npm run test:integration
  allow_failure: true

Test Code Formatting:
  stage: test
  script:
   - npm ci
   - npm run test:format
